name: Azure App Service Deploy

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Build and publish the project
      - name: Build and publish with dotnet
        run: |
          dotnet build --configuration Release
          dotnet publish ./Azure.AspNet.Web.Api/Azure.AspNet.Web.Api.csproj -c Release -o ./publish

      # Upload publish artifact
      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download publish artifact
      - name: Download publish artifact
        uses: actions/download-artifact@v4
        with:
          name: publish
          path: ./publish

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ vars.APP_SERVICE_NAME }}
          package: ./publish
