name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

env:
  AZURE_WEBAPP_NAME: ${{ vars.APP_SERVICE_NAME }}    # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './'      # Set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0.x'           # Set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 

    # Login to Azure
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create Azure Resource Group
    - name: Create Azure Resource Group
      run: |
        az group create --name ${{ vars.RESOURCE_GROUP_NAME }} \
                        --location ${{ vars.AZURE_LOCATION }}

    # Create Azure App Service
    - name: Create Azure App Service
      run: |
        az webapp create --name ${{ vars.APP_SERVICE_NAME }} \
                     --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
                     --plan ${{ vars.APP_SERVICE_PLAN_NAME }} \
                     --sku F1 \
                     --runtime "DOTNETCORE:9.0" \
                     --location ${{ vars.AZURE_LOCATION }} \
                     --os-type Linux

    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using Azure Credentials'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Azure.AspNet.Web.Api'
      
    - name: logout
      run: |
        az logout